# Generated by Django 4.0.1 on 2022-05-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='log',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
